[package]
name = "colink-protocol-remote-command"
version = "0.1.2"
edition = "2021"

[dependencies]
colink = "0.2.0"
prost = "0.10"
regex = "1.5"
tokio = "1.18"
tracing = "0.1"
uuid = { version = "0.8", features = ["v4"] }

[build-dependencies]
prost-build = "0.10"
