[package]
name = "remote_command"
version = "0.1.1"
keywords = ["remote command"]
description = "remote command"
entrypoint = "cargo run"

[remote_command]
name = "remote_command"
description = "remote command"
